# Generated by Django 4.1.7 on 2023-02-25 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_basketmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersmodel',
            name='language',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
