# Generated by Django 4.1.7 on 2023-03-01 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0007_alter_usersmodel_language"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telegram_id", models.CharField(max_length=50)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("Наличные", "Наличные"),
                            ("Click", "Click"),
                            ("Payme", "Payme"),
                        ],
                        max_length=20,
                    ),
                ),
                ("order_adress", models.CharField(max_length=200)),
                ("payment_method", models.CharField(max_length=50)),
            ],
        ),
    ]
