# Generated by Django 4.1.7 on 2023-03-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0009_alter_ordermodel_order_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersmodel",
            name="phone_number",
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
