# Generated by Django 4.1.7 on 2023-03-01 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0010_usersmodel_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("API", "Заказ передан клиенту"),
                    ("Cancel", "Заказ отменён клиентом"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
