# Generated by Django 4.1.7 on 2023-03-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0011_alter_ordermodel_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="order_items",
            field=models.TextField(null=True),
        ),
    ]
