# Generated by Django 4.1.7 on 2023-03-01 06:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0012_ordermodel_order_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="order_items",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="order_status",
            field=models.CharField(
                choices=[
                    ("Waiting", "Ожидает звонка"),
                    ("API", "Заказ передан клиенту"),
                    ("Cancel", "Заказ отменён клиентом"),
                ],
                default="Waiting",
                max_length=50,
                null=True,
            ),
        ),
    ]
