# Generated by Django 4.1.7 on 2023-03-01 06:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0014_ordermodel_order_date_alter_ordermodel_order_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="order_date",
        ),
        migrations.RemoveField(
            model_name="ordermodel",
            name="order_status",
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="payment_method",
            field=models.CharField(max_length=20),
        ),
    ]
