# Generated by Django 4.1.7 on 2023-03-03 05:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0015_remove_ordermodel_order_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ordermodel",
            old_name="order_adress",
            new_name="order_address",
        ),
    ]
