# Generated by Django 4.1.7 on 2023-03-03 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0016_rename_order_adress_ordermodel_order_address"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="order_address",
        ),
        migrations.RemoveField(
            model_name="usersmodel",
            name="language",
        ),
        migrations.AddField(
            model_name="usersmodel",
            name="user_address",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
