# Generated by Django 4.1.7 on 2023-03-04 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_ordermodel_order_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='category_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='api.categorymodel', to_field='category_name'),
        ),
        migrations.AlterField(
            model_name='categorymodel',
            name='category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='usersmodel',
            name='user_address',
            field=models.JSONField(max_length=200, null=True),
        ),
    ]
