# Generated by Django 4.1.7 on 2023-03-06 06:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0018_productmodel_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="order_address",
            field=models.JSONField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="order_status",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
