# Generated by Django 4.1.7 on 2023-03-11 05:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_ordermodel_order_address_ordermodel_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.CharField(max_length=50)),
                ('username', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='order_sum',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='order_items',
            field=models.CharField(max_length=1000),
        ),
    ]
